version: '3.8'
networks:
  postgresql-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
services:
  postgresql:
    image: postgres:10.3
    container_name: dockerpostgresql
    restart: always
    networks:
      - postgresql-network
    environment:
      - POSTGRES_USER=${__YOUR_DATABASE_USER__}
      - POSTGRES_PASSWORD=${__YOUR_DATABASE_PASSWORD__}
    volumes:
      - data-postgresql:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    expose:
      - '5432'
  prisma:
    container_name: dockerprisma
    build: 
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - postgresql-network
    command: >
      bash -c '
        npx prisma db push --schema prisma/postgresql.prisma
        npx prisma generate --schema prisma/mariadb_kangu.prisma
        npm start
      '
    depends_on:
      - postgresql
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${__YOUR_MANAGEMENT_API_SECRET__}
        port: ${__YOUR_PRISMA_SERVER_PORT__}
        databases:
          default:
            connector: ${__YOUR_DATABASE_CONNECTOR__}
            host: ${__YOUR_DATABASE_HOST__}
            port: ${__YOUR_DATABASE_PORT__}
            user: ${__YOUR_DATABASE_USER__}
            password: ${__YOUR_DATABASE_PASSWORD__}
            connectionLimit: ${__YOUR_CONNECTION_LIMIT__}
volumes:
  data-prisma:
  data-postgresql: