api:
  openapi: 3.0.3
  info:
    title: DUCK API TESTE
    description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
    version: 1.0.0
  servers:
    - url: http://localhost:3000
      description: Optional server description, e.g. Main (production) server
    - url: http://localhost:3000/
      description: Optional server description, e.g. Internal staging server for testing
api_2:
  openapi: 3.0.3
  info:
    title: API 2
    description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
    version: 1.0.0
  servers:
    - url: http://localhost:3000
      description: Optional server description, e.g. Main (production) server
    - url: http://localhost:3000/
      description: Optional server description, e.g. Internal staging server for testing
api3:
  openapi: 3.0.3
  info:
    title: DUCK API 3
    description: Super patos
    version: 1.0.0
  servers:
    - url: http://localhost:3000
      description: Optional server description, e.g. Main (production) server
    - url: http://localhost:3000/
      description: Optional server description, e.g. Internal staging server for testing
api_linkedin:
  openapi: 3.0.3
  info:
    title: API LINKEDIN
    description: Api demo linkedin
    version: 1.0.0
  servers:
    - url: http://localhost:3000
      description: Optional server description, e.g. Main (production) server
    - url: http://localhost:3000/
      description: Optional server description, e.g. Internal staging server for testing
