api_postgresql:
  openapi: 3.0.3
  info:
    title: API POSTGRESQL
    description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
    version: 1.0.0
  servers:
    - url: /
      description: Optional server description, e.g. Main (production) server
api_mariadb_kangu:
  openapi: 3.0.3
  info:
    title: API MARIADB KANGU
    description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
    version: 1.0.0
  servers:
    - url: /
      description: Optional server description, e.g. Main (production) server
